name: Configuration File Formatting

on:
  push:

jobs:
  dapperdata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6

      - name: Install Dependencies
        run: make install

      - name: Test Formatting
        run: make dapperdata_check
