name: Import Sorting

on:
  push:

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Python Version from File
        id: python_version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.python_version.outputs.version }}

      - name: Install Dependencies
        run: make install

      - name: Test Formatting
        run: make isort_check
