name: Mypy testing

on:
  push:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5

      - name: Install Dependencies
        run: make install

      - name: Test Typing
        run: make mypy_check
