name: PyPI

on:
  push:
    branches:
      - "**"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  PUBLISH_TO_PYPI: true

jobs:
  pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-python@v5

      - name: Install Dependencies
        run: make install

      - name: Build Wheel
        run: make build

      # This will only run on Tags
      - name: Publish package
        if: ${{ env.PUBLISH_TO_PYPI == 'true' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')}}
        uses: pypa/gh-action-pypi-publish@release/v1
