name: Ruff Validation

on:
  push:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6

      - name: Install Dependencies
        run: make install

      - name: Test Formatting
        run: make ruff_check
